name: Build Docker and Extract Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-image .

    - name: Extract binaries
      run: |
        docker run --rm -v "$(pwd):/output" my-image cp /path/to/binaries/* /output

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./path/to/binaries/*
