name: Build Docker and Extract Binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose to extract binaries
        run: |
          docker-compose up --build builder

      - name: List extracted binaries
        run: ls -la bin

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: myapp-binaries
          path: bin

